storageClasses:
  StructuredDataDict:
    pytype: dict
  StructuredDataList:
    pytype: list
  TablePersistable:
    pytype: lsst.afw.table.io.Persistable
  TablePersistableWcs:
    pytype: lsst.afw.geom.skyWcs.SkyWcs
  TablePersistablePsf:
    pytype: lsst.afw.detection.Psf
  TablePersistableCoaddInputs:
    pytype: lsst.afw.image.CoaddInputs
  TablePersistableVisitInfo:
    pytype: lsst.afw.image.VisitInfo
  TablePersistableApCorr:
    pytype: lsst.afw.image.ApCorrMap
  TablePersistablePhotoCalib:
    pytype: lsst.afw.image.PhotoCalib
  TablePersistableTransmissionCurve:
    pytype: lsst.afw.image.TransmissionCurve
  Camera:
    pytype: lsst.afw.cameraGeom.Camera
  Detector:
    pytype: lsst.afw.cameraGeom.Detector
  Image: &Image
    pytype: lsst.afw.image.Image
    assembler: lsst.daf.butler.assemblers.exposureAssembler.ExposureAssembler
    parameters:
      - bbox
      - origin
  ImageF:
    inheritsFrom: Image
    pytype: lsst.afw.image.ImageF
  ImageI:
    inheritsFrom: Image
    pytype: lsst.afw.image.ImageI
  ImageU:
    inheritsFrom: Image
    pytype: lsst.afw.image.ImageU
  DecoratedImage:
    pytype: lsst.afw.image.DecoratedImage
  DecoratedImageU:
    inheritsFrom: DecoratedImage
    pytype: lsst.afw.image.DecoratedImageU
  Mask:
    pytype: lsst.afw.image.Mask
    assembler: lsst.daf.butler.assemblers.exposureAssembler.ExposureAssembler
    parameters:
      - bbox
      - origin
  MaskX:
    inheritsFrom: Mask
    pytype: lsst.afw.image.MaskX
  MaskedImage:
    pytype: lsst.afw.image.MaskedImage
  MaskedImageF:
    inheritsFrom: MaskedImage
    pytype: lsst.afw.image.MaskedImageF
  MaskedImageU:
    inheritsFrom: MaskedImage
    pytype: lsst.afw.image.MaskedImageU
  MaskedImageI:
    inheritsFrom: MaskedImage
    pytype: lsst.afw.image.MaskedImageI
  Catalog:
    pytype: lsst.afw.table.BaseCatalog
  PeakCatalog:
    pytype: lsst.afw.detection.PeakCatalog
  SimpleCatalog:
    pytype: lsst.afw.table.SimpleCatalog
  SourceCatalog:
    pytype: lsst.afw.table.SourceCatalog
  ObjectMaskCatalog:
    pytype: lsst.pipe.tasks.objectMasks.ObjectMaskCatalog
  SkyMap:
    pytype: lsst.skymap.BaseSkyMap
  PropertySet:
    pytype: lsst.daf.base.PropertySet
  PropertyList:
    pytype: lsst.daf.base.PropertyList
  PropertySet:
    pytype: lsst.daf.base.PropertySet
  DefectsList:
    pytype: lsst.meas.algorithms.Defects
  Exposure:
    pytype: lsst.afw.image.Exposure
    assembler: lsst.daf.butler.assemblers.exposureAssembler.ExposureAssembler
    parameters:
      - bbox
      - origin
    components:
      image: Image
      mask: Mask
      variance: Image
      wcs: TablePersistableWcs
      psf: TablePersistablePsf
      photoCalib: TablePersistablePhotoCalib
      visitInfo: TablePersistableVisitInfo
      apCorrMap: TablePersistableApCorr
      coaddInputs: TablePersistableCoaddInputs
      transmissionCurve: TablePersistableTransmissionCurve
      metadata: PropertyList
  ExposureF:
    inheritsFrom: Exposure
    pytype: lsst.afw.image.ExposureF
    components:
      image: ImageF
      mask: MaskX
      variance: ImageF
  ExposureI:
    inheritsFrom: Exposure
    pytype: lsst.afw.image.ExposureI
    components:
      image: ImageI
      mask: MaskX
      variance: ImageF
  ExposureU:
    inheritsFrom: Exposure
    pytype: lsst.afw.image.ExposureU
    components:
      image: ImageU
      mask: MaskX
      variance: ImageF
  Background:
    pytype: lsst.afw.math.BackgroundList
  Config:
    pytype: lsst.pex.config.Config
  Packages:
    pytype: lsst.base.Packages
  NumpyArray:
    pytype: numpy.ndarray
  Thumbnail:
    pytype: numpy.ndarray
